import React from "react";
import useSwr from "swr";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  Box,
  Container,
  Heading,
  SkeletonText,
  VStack,
} from "@chakra-ui/react";
import Editor from "../../components/Editor";

const postId = () => {
  const router = useRouter();
  const postId = router.query.postId;

  const fetcher = (...args) => fetch(...args).then((res) => res.json());
  const { data, error } = useSwr(`/api/post/${postId}`, fetcher);

  if (error) return <div>Failed to load</div>;
  if (!data) {
    return (
      <Container maxW="1000px" position="relative" padding={1} boxShadow="lg">
        <SkeletonText mt="4" noOfLines={4} spacing="4" skeletonHeight="2" />
      </Container>
    );
  }

  return (
    <>
      <Head>
        <title>Articels | Detail </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW="1000px" position="relative" padding={1}>
        <VStack spacing={5} justifyContent="left" alignItems="normal">
          <Box>
            <Heading fontSize={["md", "md", "lg", "2xl"]}>
              {data?.title}
            </Heading>
          </Box>

          <Editor
            isParent={false}
            description={data?.body}
            editable={false}
            active={true}
          />
        </VStack>
      </Container>
    </>
  );
};

export default postId;
