import React from 'react';
import useSwr from 'swr';
import Head from 'next/head';
import { useRouter } from 'next/router';
import {
  Box,
  Button,
  Container,
  Heading,
  SkeletonText,
  VStack,
  Icon,
  Text,
} from '@chakra-ui/react';
import Editor from '../../components/Editor';
import { MdKeyboardArrowLeft } from 'react-icons/md';

const postId = () => {
  const router = useRouter();
  const postId = router.query.postId;

  const fetcher = (...args) => fetch(...args).then((res) => res.json());
  const { data, error } = useSwr(`/api/post/${postId}`, fetcher);

  if (error) return <div>Failed to load</div>;
  if (!data) {
    return (
      <Container maxW='1000px' position='relative' padding={3} boxShadow='lg'>
        <SkeletonText mt='4' noOfLines={20} spacing='4' skeletonHeight='5' />
      </Container>
    );
  }

  return (
    <>
      <Head>
        <title>Articels | Detail </title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Container maxW='1000px' position='relative' padding={3}>
        <VStack spacing={5} justifyContent='left' alignItems='normal'>
          <Box>
            <Heading fontSize={['3xl', '3xl', '3xl', '5xl']}>
              {data?.title}
            </Heading>
          </Box>

          <Editor
            isParent={false}
            description={data?.body}
            editable={false}
            active={true}
          />
        </VStack>

        <Button
          onClick={router.back}
          variant='solid'
          display='flex'
          alignItems='center'
          mt={5}
          mb={3}
        >
          <Icon w={5} h={5} as={MdKeyboardArrowLeft} />
          <Text>Go back</Text>
        </Button>
      </Container>
    </>
  );
};

export default postId;
