import React from "react";
import useSwr from "swr";
import Head from "next/head";
import { useRouter } from "next/router";
import StarterKit from "@tiptap/starter-kit";
import { EditorContent, useEditor } from "@tiptap/react";
import { Box, Container, Heading, VStack } from "@chakra-ui/react";

const postId = () => {
  const router = useRouter();
  const postId = router.query.postId;

  const fetcher = (...args) => fetch(...args).then((res) => res.json());
  const { data } = useSwr(`/api/post/${postId}`, fetcher);

  const editor = useEditor({
    extensions: [StarterKit],
    content: data?.body,
    editable: false,
  });

  return (
    <>
      <Head>
        <title>{`Articels | `} </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW="1000px" position="relative" padding={1}>
        <VStack spacing={5} justifyContent="left" alignItems="normal">
          <Box>
            <Heading fontSize={["md", "md", "lg", "2xl"]}>
              {data?.title}
            </Heading>
          </Box>

          <EditorContent editor={editor} disabled={true} />
        </VStack>
      </Container>
    </>
  );
};

export default postId;
