export const metadata = {
  title: "Article | Authentication",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return <section>{children}</section>;
}
