import { getServerSession } from "next-auth/next";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Article",
  description: "Generated by create next app",
};

export default async function Home() {
  const session = await getServerSession(authOptions);

  if (!session) {
    return redirect("/auth");
  }

  return <main></main>;
}

// export async function getUserSession() {
//   return {
//     props: { session },
//   };
// }
