import { getServerSession } from 'next-auth/next';
import { authOptions } from './api/auth/[...nextauth]/route';
import { redirect } from 'next/navigation';

export const metadata = {
  title: 'Article',
  description: 'Generated by create next app',
};

export default async function Home() {
  const session = await getServerSession(authOptions);

  if (!session) {
    return redirect('/auth');
  }

  return (
    <main>
      <div className="p-2 w-full h-screen fixed top-0 z-10 flex items-center justify-center">
        <h1 className="text-[4em] font-mono text-center">Share Your Story Make Life Intresting</h1>
      </div>
    </main>
  );
}
