export const metadata = {
  title: 'Article | Create Post',
  description: 'Generated by create next app',
};

export default function CreatePostLayout({ children }) {
  return <section>{children}</section>;
}
