export const metadata = {
  title: 'Article | Detail Post',
  description: 'Generated by create next app',
};

export default function DetailPostLayout({ children }) {
  return <section className="px-2 py-20 md:py-24 md:max-w-screen-xl m-auto">{children}</section>;
}
