import React from "react";
import Head from "next/head";
import {
  Box,
  Button,
  FormControl,
  FormLabel,
  Input,
  Stack,
  Text,
  Icon,
  useColorMode,
} from "@chakra-ui/react";
import { FcGoogle } from "react-icons/fc";
import { BsGithub } from "react-icons/bs";
import { MdOutlineEmail } from "react-icons/md";
import { signIn } from "next-auth/react";
import { useForm } from "react-hook-form";
import { BsCloudSun, BsFillCloudMoonFill } from "react-icons/bs";

const index = () => {
  const { register, watch, handleSubmit } = useForm();
  const { colorMode, toggleColorMode } = useColorMode();

  const googleLogin = async () => {
    signIn("google", { callbackUrl: "/" });
  };

  const githubLogin = async () => {
    signIn("github", { callbackUrl: "/" });
  };

  const onSubmit = async () => {
    await signIn("email", {
      email: watch("email"),
      callbackUrl: "/",
    });
  };

  return (
    <>
      <Head>
        <title>Authentication || Articels</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box width="100%" height="100vh" display="flex">
        <Box padding={5} width="xl" margin="auto">
          <Box display="flex" justifyContent="end">
            <Button size="sm" onClick={toggleColorMode}>
              {colorMode === "light" ? (
                <Icon w={5} h={5} as={BsCloudSun} />
              ) : (
                <Icon w={5} h={5} as={BsFillCloudMoonFill} />
              )}
            </Button>
          </Box>

          <Box>
            <Text fontSize="4xl" fontWeight="extrabold">
              Share Everything Happen
            </Text>
            <Text fontWeight="bold" fontSize="xl">
              Join Now!
            </Text>
          </Box>

          <Box marginY={5}>
            <form onSubmit={handleSubmit(onSubmit)}>
              <Stack spacing={3}>
                <FormControl>
                  <FormLabel>Email</FormLabel>
                  <Input
                    {...register("email")}
                    type="email"
                    placeholder="example@email.com"
                  />
                </FormControl>

                <Button leftIcon={<MdOutlineEmail />} type="submit">
                  Continue with Email
                </Button>
              </Stack>
            </form>
          </Box>

          <Box marginY={3}>
            <Text textAlign="center">or</Text>
          </Box>

          <Box>
            <Stack spacing={4}>
              <Button leftIcon={<FcGoogle />} onClick={googleLogin}>
                Continue with Google
              </Button>
              {/* <Button leftIcon={<BsGithub />} onClick={githubLogin}>
                Continue with Github
              </Button> */}
            </Stack>
          </Box>
        </Box>
      </Box>
    </>
  );
};

export default index;
